- id: '1644686013375'
  name: All devices off
  entities:
    light.bathroom_on_off:
      supported_color_modes:
      - onoff
      off_brightness:
      friendly_name: Bathroom
      icon: mdi:bathtub-outline
      supported_features: 8
      state: 'off'
    light.tubelight_on_off:
      supported_color_modes:
      - onoff
      off_brightness:
      friendly_name: Tubelight
      icon: mdi:bed
      supported_features: 8
      state: 'off'
    light.night_on_off:
      supported_color_modes:
      - onoff
      off_brightness:
      friendly_name: Night
      icon: mdi:weather-night
      supported_features: 8
      state: 'off'
    switch.fan_on_off:
      friendly_name: Fan
      icon: mdi:ceiling-fan
      state: 'off'
    switch.workstation_on_off:
      friendly_name: Workstation
      icon: mdi:power-plug
      state: 'off'
    switch.gaurav_laptop:
      friendly_name: Gaurav's Laptop
      icon: mdi:laptop
      assumed_state: true
      state: 'off'
    media_player.nesthubc9fc:
      friendly_name: Gaurav's Bedroom display
      supported_features: 152461
      state: 'off'
  icon: mdi:lightbulb-off
- id: '1646551898375'
  name: Gaurav Bedroom off
  entities:
    switch.fan_on_off:
      icon: mdi:ceiling-fan
      friendly_name: Fan
      state: 'off'
    light.night_on_off:
      supported_color_modes:
      - onoff
      off_with_transition: false
      off_brightness:
      icon: mdi:weather-night
      friendly_name: Night
      supported_features: 8
      state: 'off'
    light.tubelight_on_off:
      supported_color_modes:
      - onoff
      off_with_transition: false
      off_brightness:
      icon: mdi:bed
      friendly_name: Tubelight
      supported_features: 8
      state: 'off'
    switch.workstation_on_off:
      icon: mdi:desktop-tower-monitor
      friendly_name: Workstation
      state: 'off'
  icon: mdi:bed
  metadata: {}
